npm install -g typescript
2021-03-01T00:39:17.472042+00:00 app[web.1]: > umi-feeds-backend@0.1.0 build /app
2021-03-01T00:39:17.472042+00:00 app[web.1]: > npm install -g tsc && npm install
2021-03-01T00:39:17.472042+00:00 app[web.1]:
2021-03-01T00:39:18.000000+00:00 app[api]: Build succeeded
2021-03-01T00:39:18.658137+00:00 app[web.1]: npm WARN deprecated tsc@1.20150623.0: you probably meant to install typescript
2021-03-01T00:39:19.069572+00:00 app[web.1]: /app/.heroku/node/bin/tsc -> /app/.heroku/node/lib/node_modules/tsc/bin/tsc
2021-03-01T00:39:19.069820+00:00 app[web.1]: /app/.heroku/node/bin/tsserver -> /app/.heroku/node/lib/node_modules/tsc/bin/tsserver
2021-03-01T00:39:19.075282+00:00 app[web.1]: + tsc@1.20150623.0
2021-03-01T00:39:19.075283+00:00 app[web.1]: updated 1 package in 0.798s
2021-03-01T00:39:30.428268+00:00 app[web.1]: 
2021-03-01T00:39:30.428285+00:00 app[web.1]: > umi-feeds-backend@0.1.0 postinstall /app
2021-03-01T00:39:30.428286+00:00 app[web.1]: > tsc
2021-03-01T00:39:30.428286+00:00 app[web.1]:
2021-03-01T00:39:31.056961+00:00 app[web.1]: error TS5023: Unknown compiler option 'esModuleInterop'.
2021-03-01T00:39:31.056984+00:00 app[web.1]: error TS5023: Unknown compiler option 'allowSyntheticDefaultImports'.
2021-03-01T00:39:31.056984+00:00 app[web.1]: error TS5023: Unknown compiler option 'moduleResolution'.
2021-03-01T00:39:31.056985+00:00 app[web.1]: error TS5023: Unknown compiler option 'baseUrl'.
2021-03-01T00:39:31.056985+00:00 app[web.1]: error TS5023: Unknown compiler option 'paths'.
2021-03-01T00:39:31.088763+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-01T00:39:31.089097+00:00 app[web.1]: npm ERR! errno 1
2021-03-01T00:39:31.102393+00:00 app[web.1]: npm ERR! umi-feeds-backend@0.1.0 postinstall: `tsc`
2021-03-01T00:39:31.102619+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-01T00:39:31.102824+00:00 app[web.1]: npm ERR!
2021-03-01T00:39:31.102972+00:00 app[web.1]: npm ERR! Failed at the umi-feeds-backend@0.1.0 postinstall script.
2021-03-01T00:39:31.103125+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-01T00:39:31.115294+00:00 app[web.1]:
2021-03-01T00:39:31.115552+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-01T00:39:31.115683+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-01T00_39_31_106Z-debug.log
2021-03-01T00:39:31.134524+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-01T00:39:31.134916+00:00 app[web.1]: npm ERR! errno 1
2021-03-01T00:39:31.141644+00:00 app[web.1]: npm ERR! umi-feeds-backend@0.1.0 build: `npm install -g tsc && npm install`
2021-03-01T00:39:31.141815+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-01T00:39:31.142023+00:00 app[web.1]: npm ERR!
2021-03-01T00:39:31.142105+00:00 app[web.1]: npm ERR! Failed at the umi-feeds-backend@0.1.0 build script.
2021-03-01T00:39:31.142245+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-01T00:39:31.149017+00:00 app[web.1]:
2021-03-01T00:39:31.149436+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-01T00:39:31.149442+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-01T00_39_31_143Z-debug.log
2021-03-01T00:39:31.199236+00:00 heroku[web.1]: Process exited with status 1
2021-03-01T00:39:31.288823+00:00 heroku[web.1]: State changed from starting to crashed