Revert to not using npx
Previous error: 2021-03-01T00:04:47.270882+00:00 app[web.1]: > umi-feeds-backend@0.1.0 lint /app
2021-03-01T00:04:47.270884+00:00 app[web.1]: > npx tsc --noEmit && eslint "**/*.{js,ts}" --quiet --fix
2021-03-01T00:04:47.270884+00:00 app[web.1]:
2021-03-01T00:04:58.389322+00:00 app[web.1]: npx: installed 1 in 10.55s
2021-03-01T00:04:59.433006+00:00 app[web.1]: error TS5023: Unknown compiler option 'esModuleInterop'.
2021-03-01T00:04:59.433072+00:00 app[web.1]: error TS5023: Unknown compiler option 'allowSyntheticDefaultImports'.
2021-03-01T00:04:59.433117+00:00 app[web.1]: error TS5023: Unknown compiler option 'moduleResolution'.
2021-03-01T00:04:59.433162+00:00 app[web.1]: error TS5023: Unknown compiler option 'baseUrl'.
2021-03-01T00:04:59.433210+00:00 app[web.1]: error TS5023: Unknown compiler option 'paths'.
2021-03-01T00:04:59.507952+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-01T00:04:59.508682+00:00 app[web.1]: npm ERR! errno 1
2021-03-01T00:04:59.525043+00:00 app[web.1]: npm ERR! umi-feeds-backend@0.1.0 lint: `npx tsc --noEmit && eslint "**/*.{js,ts}" --quiet --fix`
2021-03-01T00:04:59.525288+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-01T00:04:59.525525+00:00 app[web.1]: npm ERR!
2021-03-01T00:04:59.525705+00:00 app[web.1]: npm ERR! Failed at the umi-feeds-backend@0.1.0 lint script.
2021-03-01T00:04:59.525915+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-01T00:05:00.028873+00:00 app[web.1]:
2021-03-01T00:05:00.039609+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-01T00:05:00.039812+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-01T00_04_59_526Z-debug.log
2021-03-01T00:05:00.199877+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-01T00:05:00.200455+00:00 app[web.1]: npm ERR! errno 1
2021-03-01T00:05:00.217340+00:00 app[web.1]: npm ERR! umi-feeds-backend@0.1.0 build: `npm run lint`
2021-03-01T00:05:00.217554+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-01T00:05:00.217789+00:00 app[web.1]: npm ERR!
2021-03-01T00:05:00.217970+00:00 app[web.1]: npm ERR! Failed at the umi-feeds-backend@0.1.0 build script.
2021-03-01T00:05:00.218166+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-01T00:05:00.577333+00:00 app[web.1]:
2021-03-01T00:05:00.577674+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-01T00:05:00.577849+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-01T00_05_00_219Z-debug.log
2021-03-01T00:05:00.676057+00:00 heroku[web.1]: Process exited with status 1
2021-03-01T00:05:00.760301+00:00 heroku[web.1]: State changed from starting to crashed
2021-03-01T00:15:17.463159+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=umi-feeds-backend.herokuapp.com request_id=9394e2eb-5759-4e5e-a71b-895bf2c5e197 fwd="104.162.62.69" dyno= connect= service= status=503 bytes= protocol=https