Try doing npm install in build
2021-03-01T00:30:06.156488+00:00 app[web.1]: Error: Cannot find module 'express-fileupload'
2021-03-01T00:30:06.156488+00:00 app[web.1]: Require stack:
2021-03-01T00:30:06.156489+00:00 app[web.1]: - /app/dist/app.js
2021-03-01T00:30:06.156489+00:00 app[web.1]: - /app/dist/server.js
2021-03-01T00:30:06.156491+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
2021-03-01T00:30:06.156492+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:725:27)
2021-03-01T00:30:06.156493+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:952:19)
2021-03-01T00:30:06.156494+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:88:18)
2021-03-01T00:30:06.156494+00:00 app[web.1]: at Object.<anonymous> (/app/dist/app.js:74:20)
2021-03-01T00:30:06.156494+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-03-01T00:30:06.156495+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-03-01T00:30:06.156495+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:928:32)
2021-03-01T00:30:06.156496+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-03-01T00:30:06.156496+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:952:19)
2021-03-01T00:30:06.156497+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:88:18)
2021-03-01T00:30:06.156497+00:00 app[web.1]: at Object.<anonymous> (/app/dist/server.js:7:31)
2021-03-01T00:30:06.156497+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-03-01T00:30:06.156498+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-03-01T00:30:06.156498+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:928:32)
2021-03-01T00:30:06.156499+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-03-01T00:30:06.156499+00:00 app[web.1]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
2021-03-01T00:30:06.156500+00:00 app[web.1]: at internal/main/run_main_module.js:17:47 {
2021-03-01T00:30:06.156500+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2021-03-01T00:30:06.156501+00:00 app[web.1]: requireStack: [ '/app/dist/app.js', '/app/dist/server.js' ]
2021-03-01T00:30:06.156501+00:00 app[web.1]: }
2021-03-01T00:30:06.197774+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-01T00:30:06.198335+00:00 app[web.1]: npm ERR! errno 1
2021-03-01T00:30:06.212845+00:00 app[web.1]: npm ERR! umi-feeds-backend@0.1.0 serve: `node dist/server.js`
2021-03-01T00:30:06.213057+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-01T00:30:06.213613+00:00 app[web.1]: npm ERR!
2021-03-01T00:30:06.213827+00:00 app[web.1]: npm ERR! Failed at the umi-feeds-backend@0.1.0 serve script.
2021-03-01T00:30:06.214022+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-01T00:30:06.229661+00:00 app[web.1]:
2021-03-01T00:30:06.230119+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-01T00:30:06.230349+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-01T00_30_06_214Z-debug.log
2021-03-01T00:30:06.306960+00:00 heroku[web.1]: Process exited with status 1
2021-03-01T00:30:06.367280+00:00 heroku[web.1]: State changed from starting to crashed